package com.fisproject.springlbd.utils;

import com.fisproject.springlbd.dto.SprintDto;
import com.fisproject.springlbd.entity.Sprint;
import com.fisproject.springlbd.repository.SprintRepository;
import com.fisproject.springlbd.service.SprintService;
import lombok.AllArgsConstructor;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Component;

import javax.transaction.Transactional;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;
import java.util.UUID;

@Component
@AllArgsConstructor
public class CreateRandomSprints {

    SprintService sprintService;


    public void create(int amount) {
        ArrayList<SprintDto> sprintDtoList = new ArrayList<>();
        Random random = new Random();

        for (int i=0; i<amount; i++) {
            int rndYear = random.nextInt(8)+1;
            int rndDay = random.nextInt(7)+1;

            SprintDto sprintDto = SprintDto.builder()
//                    .name(UUID.randomUUID().toString())
                    .name("Sprint (auto) "+i)
                    .description("Autogenerated sprint")
                    .startDate(Timestamp.valueOf("202"+rndYear+"-0"+rndDay   +"-01 00:00:00.0"))
                    .endDate(Timestamp.valueOf("202"+rndYear+"-0"+(rndDay+1) +"-01 05:00:00.0"))
                    .status(Arrays.asList(Sprint.StatusType.values()).get(random.nextInt(4)))
                    .build();
            sprintDtoList.add(sprintDto);
        }
        sprintService.addAll(sprintDtoList);
    }

}
